// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ozoneService.proto

package ozoneService;

/**
 * Protobuf type {@code ozoneService.responseByArea}
 */
public  final class responseByArea extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ozoneService.responseByArea)
    responseByAreaOrBuilder {
private static final long serialVersionUID = 0L;
  // Use responseByArea.newBuilder() to construct.
  private responseByArea(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private responseByArea() {
    city_ = "";
    index_ = 0;
    band_ = "";
    advice_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private responseByArea(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            city_ = s;
            break;
          }
          case 16: {

            index_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            band_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            advice_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ozoneService.ozoneServiceImpl.internal_static_ozoneService_responseByArea_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ozoneService.ozoneServiceImpl.internal_static_ozoneService_responseByArea_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ozoneService.responseByArea.class, ozoneService.responseByArea.Builder.class);
  }

  public static final int CITY_FIELD_NUMBER = 1;
  private volatile java.lang.Object city_;
  /**
   * <pre>
   * setCity(), getCity()
   * </pre>
   *
   * <code>string city = 1;</code>
   */
  public java.lang.String getCity() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      city_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * setCity(), getCity()
   * </pre>
   *
   * <code>string city = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCityBytes() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      city_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INDEX_FIELD_NUMBER = 2;
  private int index_;
  /**
   * <pre>
   * setIndex(), getIndex()
   * </pre>
   *
   * <code>int32 index = 2;</code>
   */
  public int getIndex() {
    return index_;
  }

  public static final int BAND_FIELD_NUMBER = 3;
  private volatile java.lang.Object band_;
  /**
   * <pre>
   * setBand(), getBand()
   * </pre>
   *
   * <code>string band = 3;</code>
   */
  public java.lang.String getBand() {
    java.lang.Object ref = band_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      band_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * setBand(), getBand()
   * </pre>
   *
   * <code>string band = 3;</code>
   */
  public com.google.protobuf.ByteString
      getBandBytes() {
    java.lang.Object ref = band_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      band_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADVICE_FIELD_NUMBER = 4;
  private volatile java.lang.Object advice_;
  /**
   * <pre>
   * setAdvice(), getAdvice()
   * </pre>
   *
   * <code>string advice = 4;</code>
   */
  public java.lang.String getAdvice() {
    java.lang.Object ref = advice_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      advice_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * setAdvice(), getAdvice()
   * </pre>
   *
   * <code>string advice = 4;</code>
   */
  public com.google.protobuf.ByteString
      getAdviceBytes() {
    java.lang.Object ref = advice_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      advice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, city_);
    }
    if (index_ != 0) {
      output.writeInt32(2, index_);
    }
    if (!getBandBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, band_);
    }
    if (!getAdviceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, advice_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, city_);
    }
    if (index_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, index_);
    }
    if (!getBandBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, band_);
    }
    if (!getAdviceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, advice_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ozoneService.responseByArea)) {
      return super.equals(obj);
    }
    ozoneService.responseByArea other = (ozoneService.responseByArea) obj;

    boolean result = true;
    result = result && getCity()
        .equals(other.getCity());
    result = result && (getIndex()
        == other.getIndex());
    result = result && getBand()
        .equals(other.getBand());
    result = result && getAdvice()
        .equals(other.getAdvice());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CITY_FIELD_NUMBER;
    hash = (53 * hash) + getCity().hashCode();
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getIndex();
    hash = (37 * hash) + BAND_FIELD_NUMBER;
    hash = (53 * hash) + getBand().hashCode();
    hash = (37 * hash) + ADVICE_FIELD_NUMBER;
    hash = (53 * hash) + getAdvice().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ozoneService.responseByArea parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ozoneService.responseByArea parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ozoneService.responseByArea parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ozoneService.responseByArea parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ozoneService.responseByArea parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ozoneService.responseByArea parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ozoneService.responseByArea parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ozoneService.responseByArea parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ozoneService.responseByArea parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ozoneService.responseByArea parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ozoneService.responseByArea parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ozoneService.responseByArea parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ozoneService.responseByArea prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ozoneService.responseByArea}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ozoneService.responseByArea)
      ozoneService.responseByAreaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ozoneService.ozoneServiceImpl.internal_static_ozoneService_responseByArea_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ozoneService.ozoneServiceImpl.internal_static_ozoneService_responseByArea_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ozoneService.responseByArea.class, ozoneService.responseByArea.Builder.class);
    }

    // Construct using ozoneService.responseByArea.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      city_ = "";

      index_ = 0;

      band_ = "";

      advice_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ozoneService.ozoneServiceImpl.internal_static_ozoneService_responseByArea_descriptor;
    }

    @java.lang.Override
    public ozoneService.responseByArea getDefaultInstanceForType() {
      return ozoneService.responseByArea.getDefaultInstance();
    }

    @java.lang.Override
    public ozoneService.responseByArea build() {
      ozoneService.responseByArea result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ozoneService.responseByArea buildPartial() {
      ozoneService.responseByArea result = new ozoneService.responseByArea(this);
      result.city_ = city_;
      result.index_ = index_;
      result.band_ = band_;
      result.advice_ = advice_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ozoneService.responseByArea) {
        return mergeFrom((ozoneService.responseByArea)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ozoneService.responseByArea other) {
      if (other == ozoneService.responseByArea.getDefaultInstance()) return this;
      if (!other.getCity().isEmpty()) {
        city_ = other.city_;
        onChanged();
      }
      if (other.getIndex() != 0) {
        setIndex(other.getIndex());
      }
      if (!other.getBand().isEmpty()) {
        band_ = other.band_;
        onChanged();
      }
      if (!other.getAdvice().isEmpty()) {
        advice_ = other.advice_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ozoneService.responseByArea parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ozoneService.responseByArea) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object city_ = "";
    /**
     * <pre>
     * setCity(), getCity()
     * </pre>
     *
     * <code>string city = 1;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * setCity(), getCity()
     * </pre>
     *
     * <code>string city = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * setCity(), getCity()
     * </pre>
     *
     * <code>string city = 1;</code>
     */
    public Builder setCity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      city_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * setCity(), getCity()
     * </pre>
     *
     * <code>string city = 1;</code>
     */
    public Builder clearCity() {
      
      city_ = getDefaultInstance().getCity();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * setCity(), getCity()
     * </pre>
     *
     * <code>string city = 1;</code>
     */
    public Builder setCityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      city_ = value;
      onChanged();
      return this;
    }

    private int index_ ;
    /**
     * <pre>
     * setIndex(), getIndex()
     * </pre>
     *
     * <code>int32 index = 2;</code>
     */
    public int getIndex() {
      return index_;
    }
    /**
     * <pre>
     * setIndex(), getIndex()
     * </pre>
     *
     * <code>int32 index = 2;</code>
     */
    public Builder setIndex(int value) {
      
      index_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * setIndex(), getIndex()
     * </pre>
     *
     * <code>int32 index = 2;</code>
     */
    public Builder clearIndex() {
      
      index_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object band_ = "";
    /**
     * <pre>
     * setBand(), getBand()
     * </pre>
     *
     * <code>string band = 3;</code>
     */
    public java.lang.String getBand() {
      java.lang.Object ref = band_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        band_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * setBand(), getBand()
     * </pre>
     *
     * <code>string band = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBandBytes() {
      java.lang.Object ref = band_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        band_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * setBand(), getBand()
     * </pre>
     *
     * <code>string band = 3;</code>
     */
    public Builder setBand(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      band_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * setBand(), getBand()
     * </pre>
     *
     * <code>string band = 3;</code>
     */
    public Builder clearBand() {
      
      band_ = getDefaultInstance().getBand();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * setBand(), getBand()
     * </pre>
     *
     * <code>string band = 3;</code>
     */
    public Builder setBandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      band_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object advice_ = "";
    /**
     * <pre>
     * setAdvice(), getAdvice()
     * </pre>
     *
     * <code>string advice = 4;</code>
     */
    public java.lang.String getAdvice() {
      java.lang.Object ref = advice_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        advice_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * setAdvice(), getAdvice()
     * </pre>
     *
     * <code>string advice = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAdviceBytes() {
      java.lang.Object ref = advice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        advice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * setAdvice(), getAdvice()
     * </pre>
     *
     * <code>string advice = 4;</code>
     */
    public Builder setAdvice(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      advice_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * setAdvice(), getAdvice()
     * </pre>
     *
     * <code>string advice = 4;</code>
     */
    public Builder clearAdvice() {
      
      advice_ = getDefaultInstance().getAdvice();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * setAdvice(), getAdvice()
     * </pre>
     *
     * <code>string advice = 4;</code>
     */
    public Builder setAdviceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      advice_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ozoneService.responseByArea)
  }

  // @@protoc_insertion_point(class_scope:ozoneService.responseByArea)
  private static final ozoneService.responseByArea DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ozoneService.responseByArea();
  }

  public static ozoneService.responseByArea getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<responseByArea>
      PARSER = new com.google.protobuf.AbstractParser<responseByArea>() {
    @java.lang.Override
    public responseByArea parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new responseByArea(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<responseByArea> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<responseByArea> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ozoneService.responseByArea getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

