// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ozoneService.proto

package ozoneService;

public interface responseByAreaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ozoneService.responseByArea)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * setCity(), getCity()
   * </pre>
   *
   * <code>string city = 1;</code>
   */
  java.lang.String getCity();
  /**
   * <pre>
   * setCity(), getCity()
   * </pre>
   *
   * <code>string city = 1;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <pre>
   * setIndex(), getIndex()
   * </pre>
   *
   * <code>int32 index = 2;</code>
   */
  int getIndex();

  /**
   * <pre>
   * setBand(), getBand()
   * </pre>
   *
   * <code>string band = 3;</code>
   */
  java.lang.String getBand();
  /**
   * <pre>
   * setBand(), getBand()
   * </pre>
   *
   * <code>string band = 3;</code>
   */
  com.google.protobuf.ByteString
      getBandBytes();

  /**
   * <pre>
   * setAdvice(), getAdvice()
   * </pre>
   *
   * <code>string advice = 4;</code>
   */
  java.lang.String getAdvice();
  /**
   * <pre>
   * setAdvice(), getAdvice()
   * </pre>
   *
   * <code>string advice = 4;</code>
   */
  com.google.protobuf.ByteString
      getAdviceBytes();
}
