// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterService.proto

package waterService;

public interface SampleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SampleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string water_sample = 1;</code>
   */
  java.lang.String getWaterSample();
  /**
   * <code>string water_sample = 1;</code>
   */
  com.google.protobuf.ByteString
      getWaterSampleBytes();

  /**
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();
}
