// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waterService.proto

package waterService;

public final class waterServiceImpl {
  private waterServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SampleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SampleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SampleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SampleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022waterService.proto\";\n\rSampleRequest\022\n\n" +
      "\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\020\n\010location\030\003 \001(" +
      "\t\"7\n\016SampleResponse\022\024\n\014water_sample\030\001 \001(" +
      "\t\022\017\n\007success\030\002 \001(\0102E\n\014waterService\0225\n\014Cr" +
      "eateSample\022\016.SampleRequest\032\017.SampleRespo" +
      "nse\"\000(\0010\001B\"\n\014waterServiceB\020waterServiceI" +
      "mplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SampleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SampleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SampleRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Location", });
    internal_static_SampleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SampleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SampleResponse_descriptor,
        new java.lang.String[] { "WaterSample", "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
