// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pm_Service.proto

package pm_Service;

public interface DensityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pm_Service.DensityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 density = 1;</code>
   */
  int getDensity();
}
