// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pm_Service.proto

package pm_Service;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pm_Service.Empty)
    com.google.protobuf.MessageOrBuilder {
}
