// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pm_Service.proto

package pm_Service;

public interface PMatterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pm_Service.PMatter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pmID = 1;</code>
   */
  java.lang.String getPmID();
  /**
   * <code>string pmID = 1;</code>
   */
  com.google.protobuf.ByteString
      getPmIDBytes();

  /**
   * <code>string status = 2;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 density = 3;</code>
   */
  int getDensity();
}
