// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pm_Service.proto

package pm_Service;

public interface RequestpmsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pm_Service.Requestpms)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool switch = 1;</code>
   */
  boolean getSwitch();
}
